# Generated by Django 5.2 on 2025-04-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('warehouse', models.CharField(max_length=10)),
                ('shelf_number', models.IntegerField()),
                ('column', models.CharField(max_length=1)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
