# Generated by Django 5.2 on 2025-04-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_level_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='column',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.CharField(),
        ),
    ]
