# Generated by Django 5.2 on 2025-04-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_column_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='level',
            field=models.CharField(max_length=10),
        ),
    ]
